name: TreeCapitator
main: com.fleynaro.treecap.Main
version: "1.0"
author: fleynaro
api: ["1.0.0"]
description: Trees by TreeCapitator!

commands:
  ftext:
    description: Write to the config floating text position
    aliases: ["ftext"]
    usage: "/ftext"
    permission: floatingtext.create

permissions:
  floatingtext.create:
    description: ""
    default: op